### ISSUE TITLE
Option to multi select filter?

### ISSUE THREAD

**Issue by mikoskinen** [ErikKalkoken/filterDropDown#2]
Thanks for a good project.

I wonder if you have any plans to support multiple filters per column? So instead of displaying a dropdownlist where user can only select one, user could multi select? 

This way user could for example filter table so that is shows personnel who are either developers or designers.

**Comment by ErikKalkoken** [comment]
thanks! glad you like my little extension for datatables.

This would indeed be an interesting feature. But it would also require some major re-design and extension of the current code. So I will put it on my list of ideas for future improvements, but I currently do not have any concrete plans to implement it.
