### ISSUE TITLE
Not working with Ajax loaded data.

### ISSUE THREAD

**Issue by chouaiebTn** [ErikKalkoken/filterDropDown#3]

**Comment by ErikKalkoken** [comment]
It works fine with Ajax loaded data in general. I use it almost exclusively that way. 
Please add details (e.g. code fragment) so I can help you with your specific issue.

**Comment by ErikKalkoken** [comment]
Since you did not provide any more details I assume this issue is no longer relevant. Please feel free to open another issue (with more detail) if you encounter a similar problem.
