### ISSUE TITLE
Export buttons

### ISSUE THREAD

**Issue by haseena321** [ErikKalkoken/filterDropDown#5]
Hi, I want to add the excel, pdf, print, copy, CSV buttons along with filter dropdowns is it possible.

**Comment by ErikKalkoken** [comment]
I have not tested this in detail, but yes. Adding buttons should work normally with this plugin. (https://www.datatables.net/extensions/buttons/)

If you encounter any specific issues please feel free to open another issue for it.

**Comment by haseena321** [comment]
Thank you for the reply, but I got the solution for this.
